services:
  student-portal-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: app-env-production
    networks:
      - app-network
    ports:
      - "2973:2973"



networks:
  app-network:
    driver: bridge